// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'character.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Character _$CharacterFromJson(Map<String, dynamic> json) => Character(
      characterId: $enumDecode(_$CharacterIdEnumMap, json['characterId']),
      primaryScript: $enumDecode(_$ScriptsEnumMap, json['primaryScript']),
      name: json['name'] as String,
      type: $enumDecode(_$CharacterTypeEnumMap, json['type']),
      alignment: $enumDecode(_$CharacterAlignmentEnumMap, json['alignment']),
      icon: $enumDecode(_$ClocktowerIconsEnumMap, json['icon']),
      description: json['description'] as String,
    );

Map<String, dynamic> _$CharacterToJson(Character instance) => <String, dynamic>{
      'characterId': _$CharacterIdEnumMap[instance.characterId]!,
      'name': instance.name,
      'type': _$CharacterTypeEnumMap[instance.type]!,
      'alignment': _$CharacterAlignmentEnumMap[instance.alignment]!,
      'icon': _$ClocktowerIconsEnumMap[instance.icon]!,
      'primaryScript': _$ScriptsEnumMap[instance.primaryScript]!,
      'description': instance.description,
    };

const _$CharacterIdEnumMap = {
  CharacterId.alignmentGood: 'alignmentGood',
  CharacterId.alignmentEvil: 'alignmentEvil',
  CharacterId.washerwoman: 'washerwoman',
  CharacterId.librarian: 'librarian',
  CharacterId.investigator: 'investigator',
  CharacterId.chef: 'chef',
  CharacterId.empath: 'empath',
  CharacterId.fortuneTeller: 'fortuneTeller',
  CharacterId.undertaker: 'undertaker',
  CharacterId.monk: 'monk',
  CharacterId.ravenkeeper: 'ravenkeeper',
  CharacterId.virgin: 'virgin',
  CharacterId.slayer: 'slayer',
  CharacterId.soldier: 'soldier',
  CharacterId.mayor: 'mayor',
  CharacterId.butler: 'butler',
  CharacterId.drunk: 'drunk',
  CharacterId.recluse: 'recluse',
  CharacterId.saint: 'saint',
  CharacterId.poisoner: 'poisoner',
  CharacterId.spy: 'spy',
  CharacterId.scarlettWoman: 'scarlettWoman',
  CharacterId.baron: 'baron',
  CharacterId.imp: 'imp',
  CharacterId.clockmaker: 'clockmaker',
  CharacterId.dreamer: 'dreamer',
  CharacterId.snakeCharmer: 'snakeCharmer',
  CharacterId.mathematician: 'mathematician',
  CharacterId.flowergirl: 'flowergirl',
  CharacterId.townCrier: 'townCrier',
  CharacterId.oracle: 'oracle',
  CharacterId.savant: 'savant',
  CharacterId.seamstress: 'seamstress',
  CharacterId.philosopher: 'philosopher',
  CharacterId.artist: 'artist',
  CharacterId.juggler: 'juggler',
  CharacterId.sage: 'sage',
  CharacterId.mutant: 'mutant',
  CharacterId.sweetheart: 'sweetheart',
  CharacterId.barber: 'barber',
  CharacterId.klutz: 'klutz',
  CharacterId.evilTwin: 'evilTwin',
  CharacterId.witch: 'witch',
  CharacterId.cerenovus: 'cerenovus',
  CharacterId.pitHag: 'pitHag',
  CharacterId.fangGu: 'fangGu',
  CharacterId.vigormortis: 'vigormortis',
  CharacterId.noDashii: 'noDashii',
  CharacterId.vortox: 'vortox',
  CharacterId.grandmother: 'grandmother',
  CharacterId.sailor: 'sailor',
  CharacterId.chambermaid: 'chambermaid',
  CharacterId.exorcist: 'exorcist',
  CharacterId.innkeeper: 'innkeeper',
  CharacterId.gambler: 'gambler',
  CharacterId.gossip: 'gossip',
  CharacterId.courtier: 'courtier',
  CharacterId.professor: 'professor',
  CharacterId.minstrel: 'minstrel',
  CharacterId.teaLady: 'teaLady',
  CharacterId.pacifist: 'pacifist',
  CharacterId.fool: 'fool',
  CharacterId.goon: 'goon',
  CharacterId.lunatic: 'lunatic',
  CharacterId.tinker: 'tinker',
  CharacterId.moonchild: 'moonchild',
  CharacterId.godfather: 'godfather',
  CharacterId.devilsAdvocate: 'devilsAdvocate',
  CharacterId.assassin: 'assassin',
  CharacterId.mastermind: 'mastermind',
  CharacterId.zombuul: 'zombuul',
  CharacterId.pukka: 'pukka',
  CharacterId.shabaloth: 'shabaloth',
  CharacterId.po: 'po',
};

const _$ScriptsEnumMap = {
  Scripts.troubleBrewing: 'troubleBrewing',
  Scripts.sectsAndViolets: 'sectsAndViolets',
  Scripts.badMoonRising: 'badMoonRising',
  Scripts.fabled: 'fabled',
  Scripts.none: 'none',
  Scripts.custom: 'custom',
};

const _$CharacterTypeEnumMap = {
  CharacterType.townsfolk: 'townsfolk',
  CharacterType.outsider: 'outsider',
  CharacterType.minion: 'minion',
  CharacterType.demon: 'demon',
  CharacterType.traveller: 'traveller',
  CharacterType.fabled: 'fabled',
  CharacterType.unkown: 'unkown',
};

const _$CharacterAlignmentEnumMap = {
  CharacterAlignment.good: 'good',
  CharacterAlignment.evil: 'evil',
  CharacterAlignment.either: 'either',
};

const _$ClocktowerIconsEnumMap = {
  ClocktowerIcons.alignmentGood: 'alignmentGood',
  ClocktowerIcons.alignmentEvil: 'alignmentEvil',
  ClocktowerIcons.scriptTroubleBrewing: 'scriptTroubleBrewing',
  ClocktowerIcons.scriptSectsAndViolets: 'scriptSectsAndViolets',
  ClocktowerIcons.scriptBadMoodRising: 'scriptBadMoodRising',
  ClocktowerIcons.characterWasherwoman: 'characterWasherwoman',
  ClocktowerIcons.characterLibrarian: 'characterLibrarian',
  ClocktowerIcons.characterInvestigator: 'characterInvestigator',
  ClocktowerIcons.characterChef: 'characterChef',
  ClocktowerIcons.characterEmpath: 'characterEmpath',
  ClocktowerIcons.characterFortuneTeller: 'characterFortuneTeller',
  ClocktowerIcons.characterUndertaker: 'characterUndertaker',
  ClocktowerIcons.characterMonk: 'characterMonk',
  ClocktowerIcons.characterRavenkeeper: 'characterRavenkeeper',
  ClocktowerIcons.characterVirgin: 'characterVirgin',
  ClocktowerIcons.characterSlayer: 'characterSlayer',
  ClocktowerIcons.characterSoldier: 'characterSoldier',
  ClocktowerIcons.characterMayor: 'characterMayor',
  ClocktowerIcons.characterButler: 'characterButler',
  ClocktowerIcons.characterDrunk: 'characterDrunk',
  ClocktowerIcons.characterRecluse: 'characterRecluse',
  ClocktowerIcons.characterSaint: 'characterSaint',
  ClocktowerIcons.characterPoisoner: 'characterPoisoner',
  ClocktowerIcons.characterSpy: 'characterSpy',
  ClocktowerIcons.characterScarlettWoman: 'characterScarlettWoman',
  ClocktowerIcons.characterBaron: 'characterBaron',
  ClocktowerIcons.characterImp: 'characterImp',
  ClocktowerIcons.characterClockmaker: 'characterClockmaker',
  ClocktowerIcons.characterDreamer: 'characterDreamer',
  ClocktowerIcons.characterSnakeCharmer: 'characterSnakeCharmer',
  ClocktowerIcons.characterMathematician: 'characterMathematician',
  ClocktowerIcons.characterFlowergirl: 'characterFlowergirl',
  ClocktowerIcons.characterTownCrier: 'characterTownCrier',
  ClocktowerIcons.characterOracle: 'characterOracle',
  ClocktowerIcons.characterSavant: 'characterSavant',
  ClocktowerIcons.characterSeamstress: 'characterSeamstress',
  ClocktowerIcons.characterPhilosopher: 'characterPhilosopher',
  ClocktowerIcons.characterArtist: 'characterArtist',
  ClocktowerIcons.characterJuggler: 'characterJuggler',
  ClocktowerIcons.characterSage: 'characterSage',
  ClocktowerIcons.characterMutant: 'characterMutant',
  ClocktowerIcons.characterSweetheart: 'characterSweetheart',
  ClocktowerIcons.characterBarber: 'characterBarber',
  ClocktowerIcons.characterKlutz: 'characterKlutz',
  ClocktowerIcons.characterEvilTwin: 'characterEvilTwin',
  ClocktowerIcons.characterWitch: 'characterWitch',
  ClocktowerIcons.characterCerenovus: 'characterCerenovus',
  ClocktowerIcons.characterPitHag: 'characterPitHag',
  ClocktowerIcons.characterFangGu: 'characterFangGu',
  ClocktowerIcons.characterVigormortis: 'characterVigormortis',
  ClocktowerIcons.characterNoDashii: 'characterNoDashii',
  ClocktowerIcons.characterVortox: 'characterVortox',
  ClocktowerIcons.characterGrandmother: 'characterGrandmother',
  ClocktowerIcons.characterSailor: 'characterSailor',
  ClocktowerIcons.characterChambermaid: 'characterChambermaid',
  ClocktowerIcons.characterExorcist: 'characterExorcist',
  ClocktowerIcons.characterInnkeeper: 'characterInnkeeper',
  ClocktowerIcons.characterGambler: 'characterGambler',
  ClocktowerIcons.characterGossip: 'characterGossip',
  ClocktowerIcons.characterCourtier: 'characterCourtier',
  ClocktowerIcons.characterProfessor: 'characterProfessor',
  ClocktowerIcons.characterMinstrel: 'characterMinstrel',
  ClocktowerIcons.characterTeaLady: 'characterTeaLady',
  ClocktowerIcons.characterPacifist: 'characterPacifist',
  ClocktowerIcons.characterFool: 'characterFool',
  ClocktowerIcons.characterGoon: 'characterGoon',
  ClocktowerIcons.characterLunatic: 'characterLunatic',
  ClocktowerIcons.characterTinker: 'characterTinker',
  ClocktowerIcons.characterMoonchild: 'characterMoonchild',
  ClocktowerIcons.characterGodfather: 'characterGodfather',
  ClocktowerIcons.characterDevilsAdvocate: 'characterDevilsAdvocate',
  ClocktowerIcons.characterAssassin: 'characterAssassin',
  ClocktowerIcons.characterMastermind: 'characterMastermind',
  ClocktowerIcons.characterZombuul: 'characterZombuul',
  ClocktowerIcons.characterPukka: 'characterPukka',
  ClocktowerIcons.characterShabaloth: 'characterShabaloth',
  ClocktowerIcons.characterPo: 'characterPo',
};
